### ISSUE TITLE
When coredump, can't show right stack. sometimes.

### ISSUE THREAD

**Issue by maomao9003** [maomao9003/Introduction-of-Algorithms#8]
Core was generated by `./algorithms_test'.
Program terminated with signal SIGSEGV, Segmentation fault.
```
#0  0x0000560bd2441c9a in ?? ()
(gdb) where
#0  0x0000560bd2441c9a in ?? ()
#1  0x0000560bd2947310 in ?? ()
#2  0x0000560bd2947250 in ?? ()
#3  0x0000560bd2947314 in ?? ()
#4  0xfffffffe00000000 in ?? ()
#5  0x00007ffc95d8b540 in ?? ()
#6  0x0000560bd244193b in ?? ()
#7  0x0000000300002775 in ?? ()
#8  0x0000560bd2946980 in ?? ()
#9  0x00007ffc95d8b540 in ?? ()
#10 0x00000002d24416dd in ?? ()
#11 0x00007ffc95d8b520 in ?? ()
#12 0x00007ffc95d8b540 in ?? ()
#13 0x00007ffc95de0d46 in gettimeofday ()
```

**Comment by maomao9003** [comment]
原因是每次coredump产生的文件都是core，第二次的覆盖了第一次core文件的一部分。
删除core再次core时，不会有次问题。
